// Appwrite client shared by the data services.
//
// None of these values are secrets — the web SDK is designed to run in the
// browser, and access is controlled by the table permissions in the Appwrite
// console (the tables below need `Read` granted to the `Any` role so visitors
// can load them without signing in).
import { Client, TablesDB } from 'appwrite';

/** Region-specific Appwrite Cloud endpoint, e.g. https://fra.cloud.appwrite.io/v1 */
const APPWRITE_ENDPOINT = 'https://fra.cloud.appwrite.io/v1';
const APPWRITE_PROJECT_ID = '6ab0fd020033d880d489';

/** Database that holds the content tables. Blog posts are not here — they are
    Markdown files in content/posts (see README). */
export const APPWRITE_DATABASE_ID = '6ab0fd87003dfef54e4b';

// Table IDs, as generated by the Appwrite console. These are the auto-assigned
// hex IDs, not readable slugs — find one in the console URL for a table:
// .../databases/tablesdb/<databaseId>/tables/<tableId>/rows
export const TABLES = {
  books: '6ab0fe66003262a3d82e',
  projects: '<PROJECTS_TABLE_ID>',
} as const;

const client = new Client()
  .setEndpoint(APPWRITE_ENDPOINT)
  .setProject(APPWRITE_PROJECT_ID);

const tablesDB = new TablesDB(client);

export { client, tablesDB };
