// Appwrite client shared by the data services.
//
// None of these values are secrets — the web SDK is designed to run in the
// browser, and access is controlled by the table permissions in the Appwrite
// console (the tables below need `Read` granted to the `Any` role so visitors
// can load them without signing in).
import { Client, TablesDB } from 'appwrite';

/** Region-specific Appwrite Cloud endpoint, e.g. https://fra.cloud.appwrite.io/v1 */
const APPWRITE_ENDPOINT = 'https://fra.cloud.appwrite.io/v1';
const APPWRITE_PROJECT_ID = '6aa3eef70024a654b97f';

/** Database that holds the three content tables. */
export const APPWRITE_DATABASE_ID = '6aa3efb7003da0d0dbeb';

// Table IDs, as generated by the Appwrite console. These are the auto-assigned
// hex IDs, not readable slugs — find one in the console URL for a table:
// .../databases/tablesdb/<databaseId>/tables/<tableId>/rows
export const TABLES = {
  books: '6aa3eff70013ea7da6c4',
  projects: '<PROJECTS_TABLE_ID>',
  blogs: '<BLOGS_TABLE_ID>',
} as const;

const client = new Client()
  .setEndpoint(APPWRITE_ENDPOINT)
  .setProject(APPWRITE_PROJECT_ID);

const tablesDB = new TablesDB(client);

export { client, tablesDB };
